config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :upcoming_events, only: [:index, :new, :create]

  get '/anxiety', to: 'mental_issue#anxiety'
  get '/depression', to: 'mental_issue#depression'
  get '/addiction', to: 'mental_issue#addiction'
  get '/anger', to: 'mental_issue#anger'
  get '/eatingdistress', to: 'mental_issue#eatingdistress'
  get '/suicidalfeelings', to: 'mental_issue#suicidalfeelings'
  
  get '/appointment_form', to: 'appointment_form#new'

  get '/mentaltest', to: 'mental_issue#test'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upcoming_event.rb
class UpcomingEvent < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointment_form_controller.rb
class AppointmentFormController < ApplicationController
	def new
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/mental_issue_controller.rb
class MentalIssueController < ApplicationController
	def anxiety
	end

	def depression
	end

	def addiction
	end

	def anger
	end

	def eatingdistress
	end

	def suicidalfeelings
	end

	def test
	end

end

app/controllers/upcoming_events_controller.rb
class UpcomingEventsController < ApplicationController
	def index
		@upcoming = UpcomingEvent.all
	end
	def new
	end
	def create
		 @event = params.require(:upcomint_event);
		 @start_tim = @event["start_time(4i)"] + ":" + @event["start_time(5i)"] ;
		 @end_tim  =  @event["end_time(4i)"] + ":" + @event["end_time(5i)"];
		 @event_dat = @event["event_date(1i)"] + "-" + @event["event_date(2i)"] + "-" + @event["event_date(3i)"];
		 @e = UpcomingEvent.new(title: @event["title"],description: @event["description"],start_time: @start_tim,
		 	end_time: @end_tim,event_date: @event_dat);
		@e.save!
		redirect_to upcoming_events_path
	end

	def edit
	end
    
    def update
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_form_helper.rb
module AppointmentFormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mental_issue_helper.rb
module MentalIssueHelper
end

app/helpers/upcoming_events_helper.rb
module UpcomingEventsHelper
end

app/views/appointment_form/new.html.erb
<div style="background-color:  #e8f6f3 ">
<center><h1 style="color: #008080">AppointmentForm</h1></center>
<div class="container" style="width: 800px">
<%= simple_form_for :upcomint_event,url: upcoming_events_path do |f| %>
  <%= f.input :Name %>
  <%= f.input :PhoneNumber %>
   <%= f.input :Doctor, collection: [ "Doctor1", "Doctor2", "Doctor3", "Doctor4"] ,:input_html => {"data-remote" => true, "data-url" => "/my_areas", "data-type" => :json} %>
  <%= f.input :AppointmenDate ,input_html: { class: 'datepicker' } %>
  <%= f.input :AvailableSlots %>
  <%= f.button :submit ,class: 'btn btn-info' %>
<% end %>
<br><br>
</div>
</div>

app/views/home/index.html.erb
 <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "anxiety.jpg", :class => "d-block w-100", :height => "600", :width => "140" %>
       <div class="carousel-caption">
       <a href="/anxiety" target="_top" class= "btn btn-xs btn-primary"><h1>Anxiety</h1></a> 
       </div>
       </div>
    <div class="carousel-item">  
      <%= image_tag "depresssion1.jpg", :class => "d-block w-100", :height => "600", :width => "140" %>

       <div class="carousel-caption">
       <a href="/depression" target="_top" class= "btn btn-xs btn-primary"><h1>Depression</h1></a> 
       </div>      
    </div>
    <div class="carousel-item">
      <%= image_tag "eating.jpg", :class => "d-block w-100", :height => "600", :width => "140" %>

       <div class="carousel-caption">
       <a href="/eatingdistress" target="_top" class= "btn btn-xs btn-primary"><h1>EatingDistress</h1></a> 
       </div>      
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div style="background-color:  #e8f6f3  ">
<div class="container">
  <br>
<h1>Overview</h1>
<hr>
<p>
  We all experience problems in our lives. Sometimes those are situational and quickly resolved. Sometimes they can be more serious and difficult to handle. Counseling Services helps students with a wide range of mental health concerns. If you or someone you know is stressed by life circumstances, experiencing mental health symptoms, or have any thoughts of suicide, please talk to a caring professional.
</p>
<p>
  However, keep in mind that the mere absence of mental health concerns does not equal positive mental health and wellness. There is a lot we can do to accentuate the positive and buffer ourselves from depression and other forms of mental concerns.
</p>
<p>
Emotional, mental, and social health often cannot be separated. They each contribute greatly to our overall well-being. Emotional health emphasizes an awareness and acceptance of one’s thoughts and feelings. Social health encompasses connecting with community, family, friends, and co-workers in ways that enrich your life and the lives of those around you.
</p>
 <br>
<h1>How are you feeling?</h1>
<hr class="nhsuk-hr">
<div class="nhsuk-grid-row">
    
 <div class="row">   
<div class="col-sm-6">
    <h2 >Help with stress, anxiety or depression</h2>
    <ul>
        
            <li><a href="/anxiety" style="color: black">Anxiety</a></li>
        
            <li><a href="/depression" style="color: black">Depreesion</a></li>
        
            <li><a href="/eatingdistress" style="color: black">EatingDistress</a></li>
        
    </ul>
</div>

<div class="col-sm-6">
    <h2 >I'm not sure how I feel</h2>
    <ul >
        
            <li><a href="/mentaltest" style="color: black">Mood self-assessment</a></li>
        
    </ul>
</div>
</div>
<br><br>

</div>
  </div>
</div>
<!-- 
<div class="nhsuk-grid-column-one-third">
    <h3 class="nhsuk-heading-s nhsuk-list-links-heading">Help with other common feelings</h3>
    <ul class="nhsuk-list nhsuk-list-links">
        
            <li><a href="/conditions/stress-anxiety-depression/feeling-lonely/">Feeling lonely</a></li>
        
            <li><a href="/conditions/stress-anxiety-depression/coping-with-bereavement/">Grief after bereavement or loss</a></li>
        
            <li><a href="/conditions/stress-anxiety-depression/controlling-anger/">Anger</a></li>
        
    </ul>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MentalHealthPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #fff">
    <%= render partial: 'shared/navigation_bar' %>
    <%= yield %>
    <%=  render partial: 'shared/footer' %>
  </body>
</html>

app/views/mental_issue/anxiety.html.erb
<div style="background-color:  #e8f6f3 ">
<center><h1 style="color: #008080">Anxiety</h1></center>
<div class="container">
<h1>Overview</h1>
<p>
Occasional anxiety is an expected part of life. You might feel anxious when faced with a problem at work, before taking a test, or before making an important decision. But anxiety disorders involve more than temporary worry or fear. For a person with an anxiety disorder, the anxiety does not go away and can get worse over time. The symptoms can interfere with daily activities such as job performance, school work, and relationships.

There are several types of anxiety disorders, including generalized anxiety disorder, panic disorder, and various phobia-related disorders.

</p>
<br><hr><br>
<h1>Signs and Symptoms</h1><br>
<h2>Generalized Anxiety Disorder</h2><br>
<p>
	People with generalized anxiety disorder (GAD) display excessive anxiety or worry, most days for at least 6 months, about a number of things such as personal health, work, social interactions, and everyday routine life circumstances. The fear and anxiety can cause significant problems in areas of their life, such as social interactions, school, and work.

    Generalized anxiety disorder symptoms include:

    Feeling restless, wound-up, or on-edge
    Being easily fatigued
    Having difficulty concentrating; mind going blank
    Being irritable
    Having muscle tension
    Difficulty controlling feelings of worry
    Having sleep problems, such as difficulty falling or staying asleep, restlessness, or unsatisfying sleep

</p> </br><br>
<h2>Panic Disorder</h2></br>
<p>
	People with panic disorder have recurrent unexpected panic attacks. Panic attacks are sudden periods of intense fear that come on quickly and reach their peak within minutes. Attacks can occur unexpectedly or can be brought on by a trigger, such as a feared object or situation.

During a panic attack, people may experience:

    Heart palpitations, a pounding heartbeat, or an accelerated heartrate
    Sweating
    Trembling or shaking
    Sensations of shortness of breath, smothering, or choking
    Feelings of impending doom
    Feelings of being out of control

People with panic disorder often worry about when the next attack will happen and actively try to prevent future attacks by avoiding places, situations, or behaviors they associate with panic attacks. Worry about panic attacks, and the effort spent trying to avoid attacks, cause significant problems in various areas of the person’s life, including the development of agoraphobia (see below).
</p><br><br>
<h2>Phobia-related disorders</h2>
<p>
	People with panic disorder have recurrent unexpected panic attacks. Panic attacks are sudden periods of intense fear that come on quickly and reach their peak within minutes. Attacks can occur unexpectedly or can be brought on by a trigger, such as a feared object or situation.

During a panic attack, people may experience:

    Heart palpitations, a pounding heartbeat, or an accelerated heartrate
    Sweating
    Trembling or shaking
    Sensations of shortness of breath, smothering, or choking
    Feelings of impending doom
    Feelings of being out of control

People with panic disorder often worry about when the next attack will happen and actively try to prevent future attacks by avoiding places, situations, or behaviors they associate with panic attacks. Worry about panic attacks, and the effort spent trying to avoid attacks, cause significant problems in various areas of the person’s life, including the development of agoraphobia (see below).
</p><br><hr><br>

<h1>Risk Factors</h1>

<p>

Researchers are finding that both genetic and environmental factors contribute to the risk of developing an anxiety disorder. Although the risk factors for each type of anxiety disorder can vary, some general risk factors for all types of anxiety disorders include:

    Temperamental traits of shyness or behavioral inhibition in childhood
    Exposure to stressful and negative life or environmental events in early childhood or adulthood
    A history of anxiety or other mental illnesses in biological relatives
    Some physical health conditions, such as thyroid problems or heart arrhythmias, or caffeine or other substances/medications, can produce or aggravate anxiety symptoms; a physical health examination is helpful in the evaluation of a possible anxiety disorder.
 </p><br>
 <div style="float: right;">
    <strong >Are you feeling any above symptoms?</strong><hr>
    <strong> Want to take a self-assessment test</strong>  <%= link_to 'Self-assessment', '/mentaltest' , class: "btn btn-xs btn-primary" %><br><br>
    <strong>  &nbsp &nbsp &nbspWant to book an appointment  &nbsp &nbsp &nbsp</strong>  <%= link_to 'AppointmentForm', '/appointment_form' , class: "btn btn-xs btn-primary" %><br>
<br><br>
</div>

</div>
</div>

app/views/mental_issue/depression.html.erb
<div style="background-color:  #e8f6f3 ">
<center><h1 style="color: #008080">Depression</h1></center>
<br>
<div class="container">
	<h1>Overview</h1>
<p>
Depression is a common mental disorder affecting more than 264 million people worldwide. It is characterized by persistent sadness and a lack of interest or pleasure in previously rewarding or enjoyable activities.  It can also disturb sleep and appetite; tiredness and poor concentration are common. Depression is a leading cause of disability around the world and contributes greatly to the global burden of disease. The effects of depression can be long-lasting or recurrent and can dramatically affect a person’s ability to function and live a rewarding life.	

The causes of depression include complex interactions between social, psychological and biological factors. Life events such as childhood adversity, loss and unemployment contribute to and may catalyse the development of depression.

Psychological and pharmacological treatments exist for moderate and severe depression. However, in low- and middle-income countries, treatment and support services for depression are often absent or underdeveloped. An estimated 76–85% of people suffering from mental disorders in these countries lack access to the treatment they need
</p>
</br><hr>
<h1>Signs and Symptoms</h1><br>
<h3 data-fontsize="22" data-lineheight="31">10 common symptoms of depression:</h3>
<p>Depression varies from person to person, but there are some common signs and symptoms. It’s important to remember that these symptoms can be part of life’s normal lows. But the more symptoms you have, the stronger they are, and the longer they’ve lasted—the more likely it is that you’re dealing with depression.</p>
<ol><li><strong>Feelings of helplessness and hopelessness.&nbsp;</strong>A bleak outlook—nothing will ever get better and there’s nothing you can do to improve your situation.</li><li><strong>Loss of interest in daily activities.&nbsp;</strong>You don’t care anymore about former hobbies, pastimes, social activities, or sex. You’ve lost your ability to feel joy and pleasure.</li>
<li><strong>Appetite or weight changes.&nbsp;</strong>Significant weight loss or weight gain—a change of more than 5% of body weight in a month.</li><li><strong>Sleep changes.&nbsp;</strong>Either insomnia, especially waking in the early hours of the morning, or oversleeping.</li>	
<li><strong>Anger or irritability.&nbsp;</strong>Feeling agitated, restless, or even violent. Your tolerance level is low, your temper short, and everything and everyone gets on your nerves.</li><li><strong>Loss of energy.&nbsp;</strong>Feeling fatigued, sluggish, and physically drained. Your whole body may feel heavy, and even small tasks are exhausting or take longer to complete.</li><li><strong>Self-loathing.&nbsp;</strong>Strong feelings of worthlessness or guilt. You harshly criticize yourself for perceived faults and mistakes.</li><li><strong>Reckless behavior.&nbsp;</strong>You engage in escapist behavior such as substance abuse, compulsive gambling, reckless driving, or dangerous sports.</li>
<li><strong>Concentration problems.&nbsp;</strong>Trouble focusing, making decisions, or remembering things.</li><li><strong>Unexplained aches and pains.&nbsp;</strong>An increase in physical complaints such as headaches, back pain, aching muscles, and stomach pain.</li></ol>
<br><hr><br>
<h2 data-fontsize="28" data-lineheight="42">What you can do to feel better</h2>
<p>When you’re depressed, it can feel like there’s no light at the end of the tunnel. But there are many things you can do to lift and stabilize your mood. The key is to start with a few small goals and slowly build from there, trying to do a little more each day. Feeling better takes time, but you can get there by making positive choices for yourself.</p>
</br>
<div style="float: right;">
	<strong >Are you feeling any above symptoms?</strong><hr>
	<strong> Want to take a self-assessment test</strong>  <%= link_to 'Self-assessment', '/mentaltest' , class: "btn btn-xs btn-primary" %><br><br>
	<strong>  &nbsp &nbsp &nbspWant to book an appointment  &nbsp &nbsp &nbsp</strong>  <%= link_to 'AppointmentForm', '/appointment_form' , class: "btn btn-xs btn-primary" %><br>
<br><br>
</div>
</div>
</div>

app/views/mental_issue/eatingdistress.html.erb
<div style="background-color:  #e8f6f3 ">
<center><h1 style="color: #008080">EatingDistress</h1></center>
<div class="container">
<h1>Overview</h1>
<p>
There is a commonly held misconception that eating disorders are a lifestyle choice. Eating disorders are actually serious and often fatal illnesses that are associated with severe disturbances in people’s eating behaviors and related thoughts and emotions. Preoccupation with food, body weight, and shape may also signal an eating disorder. Common eating disorders include anorexia nervosa, bulimia nervosa, and binge-eating disorder.
</p>
<br><hr><br>
<h1>Signs and Symptoms</h1><br>
<h2>Anorexia nervosa</h2><br>
<p>
    People with anorexia nervosa may see themselves as overweight, even when they are dangerously underweight. People with anorexia nervosa typically weigh themselves repeatedly, severely restrict the amount of food they eat, often exercise excessively, and/or may force themselves to vomit or use laxatives to lose weight. Anorexia nervosa has the highest mortality rate of any mental disorder. While many people with this disorder die from complications associated with starvation, others die of suicide.

Symptoms include:

    Extremely restricted eating
    Extreme thinness (emaciation)
    A relentless pursuit of thinness and unwillingness to maintain a normal or healthy weight
    Intense fear of gaining weight
    Distorted body image, a self-esteem that is heavily influenced by perceptions of body weight and shape, or a denial of the seriousness of low body weight

Other symptoms may develop over time, including:

    Thinning of the bones (osteopenia or osteoporosis)
    Mild anemia and muscle wasting and weakness
    Brittle hair and nails
    Dry and yellowish skin
    Growth of fine hair all over the body (lanugo)
    Severe constipation
    Low blood pressure slowed breathing and pulse
    Damage to the structure and function of the heart
    Brain damage
    Multiorgan failure
    Drop in internal body temperature, causing a person to feel cold all the time
    Lethargy, sluggishness, or feeling tired all the time
    Infertility
</p> </br><br>
<h2>Bulimia nervosa</h2></br>
<p>
    People with bulimia nervosa have recurrent and frequent episodes of eating unusually large amounts of food and feeling a lack of control over these episodes. This binge-eating is followed by behavior that compensates for the overeating such as forced vomiting, excessive use of laxatives or diuretics, fasting, excessive exercise, or a combination of these behaviors. People with bulimia nervosa may be slightly underweight, normal weight, or over overweight.

Symptoms include:

    Chronically inflamed and sore throat
    Swollen salivary glands in the neck and jaw area
    Worn tooth enamel and increasingly sensitive and decaying teeth as a result of exposure to stomach acid
    Acid reflux disorder and other gastrointestinal problems
    Intestinal distress and irritation from laxative abuse
    Severe dehydration from purging of fluids
    Electrolyte imbalance (too low or too high levels of sodium, calcium, potassium, and other minerals) which can lead to stroke or heart attack

</p><br><br>
<h2>Binge-eating disorder</h2>
<p>
   People with binge-eating disorder lose control over his or her eating. Unlike bulimia nervosa, periods of binge-eating are not followed by purging, excessive exercise, or fasting. As a result, people with binge-eating disorder often are overweight or obese. Binge-eating disorder is the most common eating disorder in the U.S.

Symptoms include:

    Eating unusually large amounts of food in a specific amount of time, such as a 2-hour period
    Eating even when you're full or not hungry
    Eating fast during binge episodes
    Eating until you're uncomfortably full
    Eating alone or in secret to avoid embarrassment
    Feeling distressed, ashamed, or guilty about your eating
    Frequently dieting, possibly without weight loss

</p><br><hr><br>

<h1>Risk Factors</h1>

<p>
Eating disorders can affect people of all ages, racial/ethnic backgrounds, body weights, and genders. Eating disorders frequently appear during the teen years or young adulthood but may also develop during childhood or later in life. These disorders affect both genders, although rates among women are higher than among men. Like women who have eating disorders, men also have a distorted sense of body image.

Researchers are finding that eating disorders are caused by a complex interaction of genetic, biological, behavioral, psychological, and social factors. Researchers are using the latest technology and science to better understand eating disorders.

One approach involves the study of human genes. Eating disorders run in families. Researchers are working to identify DNA variations that are linked to the increased risk of developing eating disorders.

Brain imaging studies are also providing a better understanding of eating disorders. For example, researchers have found differences in patterns of brain activity in women with eating disorders in comparison with healthy women. This kind of research can help guide the development of new means of diagnosis and treatment of eating disorders.

 </p><br><hr>
 <h1>Treatments and Therapies</h1><br>
 <p>
 It is important to seek treatment early for eating disorders. People with eating disorders are at higher risk for suicide and medical complications. People with eating disorders can often have other mental disorders (such as depression or anxiety) or problems with substance use. Complete recovery is possible.

Treatment plans are tailored to individual needs and may include one or more of the following:

    Individual, group, and/or family psychotherapy
    Medical care and monitoring
    Nutritional counseling
    Medications
</p><br>
<div style="float: right;">
    <strong >Are you feeling any above symptoms?</strong><hr>
    <strong> Want to take a self-assessment test</strong>  <%= link_to 'Self-assessment', '/mentaltest' , class: "btn btn-xs btn-primary" %><br><br>
    <strong>  &nbsp &nbsp &nbspWant to book an appointment  &nbsp &nbsp &nbsp</strong>  <%= link_to 'AppointmentForm', '/appointment_form' , class: "btn btn-xs btn-primary" %><br>
<br><br>
</div>
</div>
</div>

app/views/mental_issue/test.html.erb
<div style="background-color:  #e8f6f3 ">
<center>
	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeFRg81h2_M0H07aT4rPjZIUjn9zZNTVxFCUmPlrZvYMlH92w/viewform?embedded=true" width="1000" height="3466" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
</center>
</div>`

app/views/shared/_footer.html.erb
<body class="d-flex flex-column min-vh-100">
    <div class="wrapper flex-grow-1"></div>
<footer class="page-footer font-small" style="background-color: #343a40">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <!-- Grid column -->

      <!-- <hr class="clearfix w-100 d-md-none pb-3"> -->

      <!-- Grid column -->
      <div class="col-md-2">

        <!-- Links -->
        <ul class="list-unstyled">
          <li>
            <a href="#!" style="color:  #000000 "><h4>About Us</h4></a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 ">

        <!-- Links -->

        <ul class="list-unstyled">
          <li>
            <a href="#!" style="color: #000000 "><h4>Contact Us</h4></a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/">IIITHYDERABAD</a>
  </div>
  <!-- Copyright -->

</footer>
</body>
<!-- Footer -->

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="/">MentalHealthSupport</a>

  <!-- Links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        MentalIssues
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/anxiety">Anxiety</a>
        <a class="dropdown-item" href="/depression">Depression</a>
        <!-- <a class="dropdown-item" href="/addiction">Addiction<a> -->
        <!-- <a class="dropdown-item" href="/anger">Anger<a> -->
        <a class="dropdown-item" href="/eatingdistress">EatingDistress<a>
        <!-- <a class="dropdown-item" href="/suicidalfeelings">SuicidalFeelings<a> -->


      </div>
    </li>
    
    <li class="nav-item">
      <a class="nav-link" href="/mentaltest">MentalTest</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="<%= upcoming_events_path %>">UpcomingEvents</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="/appointment_form">AppointmentForm</a>
    </li>

    <!-- Dropdown -->

  </ul>
</nav> 

app/views/upcoming_events/index.html.erb
<!-- <div style="background-color:  #e8f6f3 "> -->
<center><h1 style="color: #008080">UpcomingEvents</h1></center>
<div class="container">
<% @upcoming.each do |event| %>
<div class="row">
	<div class= "col" >
		<ul>
 <li> <h1><%= event.title %> </h1>
  <%= event.start_time %>
  <%= event.end_time %>
  <%= event.event_date %></li>
</ul>
</div>
</div>
<% end %>
<h3><%= link_to 'Add Event', new_upcoming_event_path %></h3>
</div>
</div>

app/views/upcoming_events/new.html.erb
<div class="container">
<center><h1 style="color: #008080">Add an Upcoming Event</h1></center>
<%= simple_form_for :upcomint_event,url: upcoming_events_path do |f| %>
  <%= f.input :title , label: 'Event' %>
  <%= f.input :description %>
  <%= f.input :event_date, as: :date %>
  <%= f.input :start_time,as: :time%>
  <%= f.input :end_time,as: :time %>
  <%= f.button :submit ,class: 'btn btn-info' %>
<% end %>
<br><br>
</div>